### ISSUE TITLE
external task_role and task_exec_role must exist before first run.

### ISSUE THREAD

**Issue by mrsufgi** [cloudposse/terraform-aws-ecs-alb-service-task#123]
## Describe the Bug
When specifing either task_role or task_exec_role terraform fails with the infamous "count" error:
```
The "count" value depends on resource attributes that cannot be determined
until apply...
```
This is due to: 
```
count = local.enabled && length(var.task_role_arn) == 0 ? 1 : 0
```
you can work around it by using -target ofc.

## Expected Behavior
working without using -target.

How about solving this using a different variable such as:
```tf
use_external_task_role: bool
use_external_task_exec_role: bool 
```

To determine the creation of task_role / task_exec_role.
I assume this would fix it.

**Comment by irvintim** [comment]
Is there a workaround for this issue?

**Comment by mrsufgi** [comment]
if I remember correctly, I solved this using the -target flag. created the resources graduallly. we could issue a fix, waiting for maintainers notes on this

**Comment by jonra1993** [comment]
Hello @mrsufgi where did you use the  **-target flag**?

**Comment by mrsufgi** [comment]
When I ran tf apply
