### ISSUE TITLE
Unable to use source_security_group_id with security_group_rules

### ISSUE THREAD

**Issue by inhumantsar** [cloudposse/terraform-aws-ecs-alb-service-task#126]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The objects in security_group_rules must match one another perfectly or else Terraform complains: https://github.com/hashicorp/terraform/issues/26265

## Expected Behavior
Able to actually create security group rules.

## Steps to Reproduce

Use anything but `cidr_blocks` in security_group_rules:

```hcl
  security_group_rules = [
    {
      type                     = "egress"
      from_port                = 0
      to_port                  = 0
      protocol                 = -1
      cidr_blocks              = ["0.0.0.0/0"]
      description              = "Allow all outbound traffic"
    },
    {
      type                     = "ingress"
      from_port                = local.container_port
      to_port                  = local.container_port
      protocol                 = "tcp"
      source_security_group_id = local.alb_security_group
      description              = "Enables incoming ALB traffic."
    }
  ]
```

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.51.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/github v3.0.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

**Comment by inhumantsar** [comment]
Also, shouldn't these have been updated in the PR that made the switch to `security_group_rules`?

* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/main.tf#L445
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/main.tf#L530

**Comment by nitrocode** [comment]
You may want to use the older v0.56.0 while the security group module has completed it's refactoring.

The 0.57.0 and 0.58.0 are pre-releases.

**Comment by inhumantsar** [comment]
I ran into this issue while working on the PR I put in around the same time. I based the PR on master rather than 0.56.0 and hit on this in testing. The branch I'm actually using was rebased on to 0.56.0. 

Filed this to point out that there are significant showstopping bugs present in those pre-releases.

**Comment by Nuru** [comment]
Obsoleted by #155
