### ISSUE TITLE
A managed resource "aws_security_group" "ecs_service" has not been declared in module.ecs_alb_service_task.

### ISSUE THREAD

**Issue by fentonfentonfenton** [cloudposse/terraform-aws-ecs-alb-service-task#139]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
```
  on .terraform/modules/ecs_alb_service_task/main.tf line 435, in resource "aws_ecs_service" "ignore_changes_task_definition_and_desired_count":
 435:       security_groups  = compact(concat(var.security_group_ids, aws_security_group.ecs_service.*.id))

A managed resource "aws_security_group" "ecs_service" has not been declared in
module.ecs_alb_service_task.

Releasing state lock. This may take a few moments...
```

## Suggested change

https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/140 PR here.

`security_groups  = compact(concat(var.security_group_ids, aws_security_group.ecs_service.*.id))`
find and replace with
`security_groups = compact(concat(module.security_group.*.id, var.security_groups))`

## Why!!!?
Looks like there's a bug in the code if you use the `ignore` `desired_count` and `task_definition` flags! 😨 

Setting `var.ignore_changes_task_definition` or `var.ignore_changes_desired_count` or both(?) to `true` results in and error:

```
A managed resource "aws_security_group" "ecs_service" has not been declared in
module.ecs_alb_service_task.
```
I think that error makes sense as we don't have a `aws_security_group.ecs_service` resource in the module.

I took at look at the code [further down at](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/0922981957cfd72aa80c363c263cf54394a518f2/main.tf#L620) (the `default`)

and that (and this is what the tests use) references the `module` `security_group`: module.security_group.*.id

Which does exist 👍

**Comment by dsonawane934** [comment]
managed resource "aws_security_group" "vprofile-bean-elb-sg" has not been declared in the root module.
