### ISSUE TITLE
Terraform Cloud - module ecs_alb_service_task has a broken symlink

### ISSUE THREAD

**Issue by tom126p** [cloudposse/terraform-aws-ecs-alb-service-task#141]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

When running in Terraform cloud the below error is a result:
failed pulling filesystem: ssh: failed parsing message: failed scanning message: expected integer

Running it locally on my laptop it works fine, only issue is VCS --> Terraform Cloud execution.

I was able to find that the module ecs_alb_service_task has a broken symlink:

vagrant@ubuntu:~/ticket58305/service-7$ find . -type l -exec ls -la {} \;
lrwxrwxrwx 1 vagrant vagrant 34 Oct 20 23:20 ./.terraform/modules/ecs_alb_service_task/terraform-aws-ecs-alb-service-task -> terraform-aws-ecs-alb-service-task

## Steps to Reproduce
1. Go to https://app.terraform.io/
2. Run terraform-aws-ecs-alb-service-task module with Remote build
3. Enter '....'
4. See error: failed pulling filesystem: ssh: failed parsing message: failed scanning message: expected integer

## Screenshots
If applicable, add screenshots or logs to help explain your problem.
See Attached log file.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Terraform v1.0.9-->  linux_amd64
 - Version: "cloudposse/ecs-alb-service-task/aws" --> "0.58.0"

## Additional Context
Add any other context about the problem here
[run-kreVEvVqQPJMawqm-plan-log.txt](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/files/7387846/run-kreVEvVqQPJMawqm-plan-log.txt)
.

**Comment by tom126p** [comment]
In Version 0.57.0 it is working fine

module "ecs_alb_service_task" {
  source                             = "cloudposse/ecs-alb-service-task/aws"
  version                            = "0.57.0"

**Comment by joshmello** [comment]
+1

**Comment by Gowiem** [comment]
@tom126p I'm assuming this is a one-off error with TFC... Are you still running into this? Or did it resolve? The module itself doesn't have say in the symlinking, so that is why I'm assuming this is on TFC's side. 

Let me know if you want to keep this open and if so then please provide some additional information.
