### ISSUE TITLE
module.this.id not defined

### ISSUE THREAD

**Issue by notchjpl** [cloudposse/terraform-aws-ecs-alb-service-task#210]
### Describe the Bug

The family parameter is failing as the module.this has not output named id and I get this error:

Error: invalid value for family (see https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html)
│
│ with module.ecs_clusters["xxxxxxxx"].module.ecs_service["xxxxxx"].aws_ecs_task_definition.default[0],
│ on .terraform/modules/ecs_clusters.ecs_service/main.tf line 51, in resource "aws_ecs_task_definition" "default":
│ 51: family = module.this.id

Both mandatory parameters are set in the module call.

### Expected Behavior

family parameter should be provisioned as there's no variable defined to provide it.

### Steps to Reproduce

Define a container definition resource and provide the parameters.

### Environment

OSX, terraform 1.5.3, ecs-alb-service-task 0.71.0

### Additional Context

context is optional, but I had to provide it to avoid the error

**Comment by debojyotig-int** [comment]
Hi @notchjpl ,

How you are able to solve this? I am still getting the same issue. Update: If I define output on module.this.id, I am getting proper output e.g: dev, but still while calling the ecs_alb_service_task getting error

 Error: expected length of family to be in the range (1 - 255), got 
 & 
Error: invalid value for family (see https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html)

**Comment by nitrocode** [comment]
Try setting the name input
