### ISSUE TITLE
Invalid Network Configuration for "Bridge" network type

### ISSUE THREAD

**Issue by ryanhobsonsmith** [cloudposse/terraform-aws-ecs-alb-service-task#22]
I'm getting the following error when trying to setup a service task with `network_mode = "bridge"`: 

```
aws_ecs_service.default: InvalidParameterException: Network Configuration is not valid for the given networkMode of this task definition.
```

Per the terraform [aws_ecs_service docs](/https://www.terraform.io/docs/providers/aws/r/ecs_service.html) it looks like you can't specify a `network_configuration` block for ecs_services unless you are using the service in `awsvpc` networking mode. 

I'm going to fork and modify to fit our needs, but would be great to get an update/example of how to use this with a bridge network configuration.

**Comment by osterman** [comment]
We have not tested it in any mode other than `awsvpc`

**Comment by aknysh** [comment]
@ryanhobsonsmith thanks!
Once you modify it and tested, could you open a PR so we get your updates into the repo?
thanks

**Comment by ryanhobsonsmith** [comment]
@aknysh so, I may be mistaken, but at least until terraform 0.12 is released, I'm pretty sure the only way to work around this limitation would be to define a (mostly) duplicate  aws_ecs_service block and then dynamically set the `count` parameter to 1 or 0 for each block based on a conditional check to network type correct? 

Given that you're already doing this for the "ignore changes" setting, then adding this in would mean that this repo would end up with 4 different aws_ecs_service definitions right? Idk, that starts to feel kind of hacky and unmaintainable to me.

Since I also was going to need a way to specify the service placement constraint block for our service, I just bit the bullet and just put in the raw resource definitions we needed into our terraform code instead of relying/adapting this module. 

Once 0.12 release is out of beta though, then maybe we can revisit.

**Comment by gauravbrills** [comment]
> @aknysh so, I may be mistaken, but at least until terraform 0.12 is released, I'm pretty sure the only way to work around this limitation would be to define a (mostly) duplicate aws_ecs_service block and then dynamically set the `count` parameter to 1 or 0 for each block based on a conditional check to network type correct?
> 
> Given that you're already doing this for the "ignore changes" setting, then adding this in would mean that this repo would end up with 4 different aws_ecs_service definitions right? Idk, that starts to feel kind of hacky and unmaintainable to me.
> 
> Since I also was going to need a way to specify the service placement constraint block for our service, I just bit the bullet and just put in the raw resource definitions we needed into our terraform code instead of relying/adapting this module.
> 
> Once 0.12 release is out of beta though, then maybe we can revisit.

yup did the same in a module to fix for bridge mode can do a PR
