### ISSUE TITLE
Please add support for health_check_grace_period_seconds as a variable

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/terraform-aws-ecs-alb-service-task#3]
This is needed for container that take time to start up.

**Comment by osterman** [comment]
@mike-zipit thanks for reporting!

Yes, I can see this as a pretty common requirement. We use a similar option in k8s all the time.

**Comment by osterman** [comment]
https://www.terraform.io/docs/providers/aws/r/ecs_service.html#health_check_grace_period_seconds

**Comment by lpil** [comment]
Looks like we can close this? :)

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/19
