### ISSUE TITLE
Defining Multiple Host Volumes Paths

### ISSUE THREAD

**Issue by TRReeve** [cloudposse/terraform-aws-ecs-alb-service-task#36]
Terraform v 0.12.7

I am getting the following issue when trying to define multiple volumes for one service.

> Error: Unsupported argument
> 
>   on .terraform/modules/batch_environment-dev.workers.airflow-webserver.alb_service_task/main.tf line 51, in resource "aws_ecs_task_definition" "default":
>   51:   volume                   = "${var.volumes}"
> 
> An argument named "volume" is not expected here. Did you mean to define a
> block of type "volume"?

```

`  volumes = [ {
    name = "content1"
    host_path = "mnt/folder1"

  },
    {
      name = "content2"
      host_path = "mnt/folder2"
    }
  ]

module "alb_service_task" {

  source = "git::https://github.com/cloudposse/terraform-aws-ecs-alb-service-task.git?ref=master"
  namespace = "namespace"
  stage = var.environment_name
  name = local.service_name
  alb_security_group = var.alb_security_group_arn
  container_definition_json = module.container_definition.json
  ecs_cluster_arn = var.ecs_cluster_id
  launch_type = var.launch_type
  vpc_id = var.vpc_id
  security_group_ids = var.security_group_ids
  subnet_ids = var.subnet_ids
  volumes = var.volumes

}
```

The problem I see is coming from here 

```
`
resource "aws_ecs_task_definition" "default" {
  family                   = "${module.default_label.id}"
  container_definitions    = "${var.container_definition_json}"
  requires_compatibilities = ["${var.launch_type}"]
  network_mode             = "${var.network_mode}"
  cpu                      = "${var.task_cpu}"
  memory                   = "${var.task_memory}"
  execution_role_arn       = "${aws_iam_role.ecs_exec.arn}"
  task_role_arn            = "${aws_iam_role.ecs_task.arn}"
  tags                     = "${module.default_label.tags}"
  volume                   = "${var.volumes}"
}`
```

In the terraform documentation for the module it only ever seems to show it with volumes individually defined as blocks and the concept of multiple volumes being joined doesn't seem to be mentioned. My use case is an airflow cluster where all nodes have access to a shared set of code and then seperate volumes for each engineering domain where they define their individual code bases. 

I was actually having a go at using this module in addition to container definitions as I was wondering if you guys might have solved the issue I've with defining task/service volumes that the terraform api doesn't seem to play nicely with passing in a list of volumes maps rather than defining the volumes seperately. Is there something I'm missing or any ideas for workarounds to this?

**Comment by TRReeve** [comment]
For anyone else who looks I managed to make a workaround for this using the task definitions module directly using the "dynamic" parameter which looks like 

`resource "aws_ecs_task_definition" "task" {
  family                = local.task_def_name
  container_definitions = module.container_definition.json
  execution_role_arn    = var.iam_execution_role_arn
  task_role_arn         = var.iam_task_role_arn

  dynamic "volume" {
    for_each = [for v in var.volumes: {
      name = v.name
      host_path = v.host_path
    }]

    content {
      name = volume.value.name
      host_path = volume.value.host_path
    }
  }

  placement_constraints {
    type       = "memberOf"
    expression = "attribute:ecs.vpc-id == ${var.vpc_id}"
  }
}`

I got this solution from this documentation [here](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks)

**Comment by aknysh** [comment]
we converted the module to TF 0.12 https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/releases/tag/0.17.0 and added `dynamic "volume"`. 
Will close the issue for now, please reopen if any problems with the new version
