### ISSUE TITLE
Variable ecs_load_balancers definition

### ISSUE THREAD

**Issue by mikalai-t** [cloudposse/terraform-aws-ecs-alb-service-task#38]
Hello. First of all, thank you much for the module!

Not sure if this is a bug, but trying to attach Target Group via `ecs_load_balancers` block raised the error, even with both possible definitions, see below:

### Terraform Version
```
Terraform v0.12.12
```

#### First try:
```hcl
module "ecs_alb_service_task" {
//...
  ecs_load_balancers          = [
    {
      target_group_arn  = join("", aws_lb_target_group.module_tg.*.arn)
      container_name    = var.container_name
      container_port    = var.container_port
    }
  ]
//...
}
```
#### Crash Output
```hcl
Error: Invalid value for module argument
...
The given value is not suitable for child module variable "ecs_load_balancers"
...
element 0: attribute "elb_name" is required.
```

Well...

#### Second try - add `elb_name`:
```hcl
module "ecs_alb_service_task" {
//...
  ecs_load_balancers          = [
    {
      elb_name = "some_value"
      target_group_arn  = join("", aws_lb_target_group.module_tg.*.arn)
      container_name    = var.container_name
      container_port    = var.container_port
    }
  ]
//...
}
```
#### Crash Output
```hcl
Error: InvalidParameterException: loadBalancerName and targetGroupArn cannot both be specified. You must specify either a loadBalancerName or a targetGroupArn.
	status code: 400, request id: ...
... in resource "aws_ecs_service" "default":
```

As a workaround cloned a module and removed `elb_name` from `variables.tf`. Since the module called _...**alb**-service-task_ think that ELB isn't so important :)

**Comment by aknysh** [comment]
set `elb_name` to `null`.
It's required by the var definition and is required for classic load balancer.
For ALB it's not required (instead, target group ARN is used), but since it's in the var definition, you have to provide some value, and `null` tells terraform to ignore it

**Comment by mikalai-t** [comment]
Now it's clear. Thank you a lot!
