### ISSUE TITLE
Need ability to customize ecs_execution_role with additional permissions

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/terraform-aws-ecs-alb-service-task#4]
The task execution role may need additional customization to allow plans with additional security needs.  

I achieved this (though I'm not sure this is the best approach) by doing:

In my `main.tf` calling `terraform-aws-ecs-alb-service-task`:
```
data "aws_iam_policy_document" "ecs_allow_ssm_access" {
  statement {
    sid       = "2"
    effect    = "Allow"
    resources = ["arn:aws:ssm:${var.aws_region}:${var.aws_account_id}:parameter/${var.stage}*"]
    actions   = [
      "ssm:List*",
      "ssm:Get*",
      "ssm:Describe*"
    ]
  }
}


module "ecs_alb_service_task" {
  ....
  custom_policy_document    = "${data.aws_iam_policy_document.ecs_allow_ssm_access.json}"`
}
```

And in `main.tf` inside this module:
```
data "aws_iam_policy_document" "ecs_execution_role" {
  source_json = "${var.custom_policy_document}"

  statement {
    sid       = "vLMpjauEwiCGsAJ9tJKsbSgn"
    effect    = "Allow"
    resources = ["*"]

    actions = [
      "ecr:GetAuthorizationToken",
      "ecr:BatchCheckLayerAvailability",
      "ecr:GetDownloadUrlForLayer",
      "ecr:BatchGetImage",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]
  }
}
```

**Comment by osterman** [comment]
@mike-zipit thanks for reporting!

IMO, we should solve this by adding an `output` for the IAM role. Then you can use `iam_role_policy_attachment` to attach as many policies as you want. 

https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html

@aknysh any input?

**Comment by k911** [comment]
@osterman @aknysh I think this issue should be closed because outputs for IAM Role have been added https://github.com/cloudposse/terraform-aws-ecs-alb-service-task#outputs (probably a long ago)

**Comment by aknysh** [comment]
yes thanks @k911 
closing the issue
