### ISSUE TITLE
Question: How To Integrate with ALB

### ISSUE THREAD

**Issue by archenroot** [cloudposse/terraform-aws-ecs-alb-service-task#41]
The name here of plugin suggest application load balancer, but this module does not create it its just used to reference existing balancer to be used with services/tasks, right?

So I should first create balancer via other module?

Thanks.

Ladislav

**Comment by jamengual** [comment]
you can use this : 
https://github.com/cloudposse/terraform-aws-alb

to create the alb and yes this module does not create an alb for you, you need to create it before hand.

**Comment by aknysh** [comment]
@archenroot 
take a look at this example (working and tested on AWS) https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/master/examples/complete/main.tf#L42

`terraform-aws-ecs-web-app` uses `terraform-aws-ecs-alb-service-task` https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/master/main.tf#L84

**Comment by archenroot** [comment]
Thank you very much for hints.

**Comment by archenroot** [comment]
I think I will base my solution on ecs-web-app module, its more all covering.

Maybe one thing to discuss. Do you secure your ECS clusters running backend api with API gateway or its additional over engineering?

**Comment by jamengual** [comment]
I think that is offtopic of what this module does.
closing
