### ISSUE TITLE
InvalidParameterException: The target group with targetGroupArn does not have an associated load balancer

### ISSUE THREAD

**Issue by drselump14** [cloudposse/terraform-aws-ecs-alb-service-task#46]
Randomly got this error. I've found that we need to  put `depends_on` but don't know howw to do it. Any help would be appreciated.   Thanks!

**Comment by cutecycle** [comment]
And here I was thinking, "why doesn't theirs need it!?"

**Comment by jamengual** [comment]
the depends_on will be to wait for the load balancer to be ready and this module does not do that and it is not possible to do in tf.12 to use depends_on between modules.

**Comment by nitrocode** [comment]
Perhaps we can document this. We could say to make sure to target apply the load balancer prior to target apply this module to prevent this error.

**Comment by nitrocode** [comment]
https://www.terraform.io/docs/language/meta-arguments/depends_on.html

> Version note: Module support for depends_on was added in Terraform 0.13, and previous versions can only use it with resources.

I think it's safe to close this.
