### ISSUE TITLE
Use AWS service role instead of creating our own

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-ecs-alb-service-task#60]
## Describe the Feature

Use AWS service role instead of creating our own

https://console.aws.amazon.com/iam/home?region=us-west-2#/roles/AWSServiceRoleForECS

## Expected Behavior

Reuse an existing role instead of creating our own

## Use Case

Why create a resource if we don't have to?

## Describe Ideal Solution

Module either takes an input for the service role and/or uses the aws service role

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by jamengual** [comment]
the only problem I see with this is that the policy : 

```
 ],
            "Resource": "*"
        },
```

allow ECS permissions to all resources, which you might not want.

I think to give the ability to pass this role or another custom role is better.

**Comment by nitrocode** [comment]
Good point and we can already do this using take_role_arn and task_exec_role_arn.
