### ISSUE TITLE
Multi-container task definition

### ISSUE THREAD

**Issue by yariksheptykin** [cloudposse/terraform-aws-ecs-alb-service-task#69]
## Multi-container task definition

The current module implementation [assumes one container](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/main.tf#L37) per tast definition. AWS however allows multiple container definitions per single tast. `terraform-aws-ecs-alb-service-task` Module [demonstrates](https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/examples/multiple_definitions/main.tf#L51) how multiple container definitions can be combined to achieve this.

It is technically possible to use an array of definitions as the argument for `container_definition_json`. For example:
```
module "ecs_alb_service_task" {
    ...
    container_definition_json = "[${module.first_container.json_map_encoded},${module.second_container.json_map_encoded}]"
    ...
  }
```

This however seems more like a workaround rather than expected solution. 

## Use Case

We are deploying an appilcation consisting of nginx, php-fpm, and nodejs (frontend api). All these containers composit one application and must behave as one and scale as one unit.

## Describe Ideal Solution

Ideally module definition would accept `container_definitions` (emphasis trailing `s`) instead of `container_definition`. For example:

```
module "ecs_alb_service_task" {
    ...
    container_definitions_json = [module.first_container.json, module.second_container.json]
    ...
  }
```
Variable descriptions should reflect this ability and provide examples.

## Alternatives Considered

The two alternatives considered are: 1) use multiple services (single container per task, service) 2) stuff multiple definitions into `container_definition_json`.

Solution (1)  is not quite applicable to our use-case due to extreme additional complexity. Solution (2) would work, however it feels more like shoehorning.

## Additional Context

I would be interested in working on a MR if this sounds like a reasonable project. Are there any issues in implementing this?

**Comment by yariksheptykin** [comment]
@osterman , is this feature worth pursuing in an MR? Anything that speaks against placing multiple container definitions into a single task with this module?

**Comment by nitrocode** [comment]
You can use this to make it look cleaner

```
module "ecs_alb_service_task" {
  ...
  container_definition_json = jsonencode([
    module.first_container.json_map_object,
    module.second_container.json_map_object,
  ])
  ...
```

**Comment by yariksheptykin** [comment]
Thanks for a quick reply @nitrocode ! Now that I see your example it occures to me that renaming a module attribute would introduce a breaking change and force everybody to upgrade to the new attribute name. This change is not worth it.

How about we add the example you provided to the README to demostrate the "official" way of using multiple container definitions?
