### ISSUE TITLE
Use name_prefix and create_before_destroy on security groups

### ISSUE THREAD

**Issue by ac-hibbert** [cloudposse/terraform-aws-ecs-alb-service-task#77]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

It can be a pain when the security group name changes as it would not be able to destroy - potentially using this pattern would work - https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L34

## Expected Behavior

Able to create new security group and assign it prior to destroy

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by nitrocode** [comment]
@ac-hibbert i added the create before destroy logic but not the name prefix. Let's see if this logic is enough to unblock you. I don't want to add the name prefix unless we have to because it will cause everyone's security group to be recreated.

**Comment by nitrocode** [comment]
Reply back if this is still relevant and we can reopen
