### ISSUE TITLE
ignore is not working as expected

### ISSUE THREAD

**Issue by mhmdio** [cloudposse/terraform-aws-ecs-alb-service-task#93]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
`tash_definition` ignore is not working as expected tf version 0.14.5

## Expected Behavior
tash_definition should be ignored

![Taskfile yml — AES 2021-01-25 at 1 51 45 PM](https://user-images.githubusercontent.com/11231023/105710033-38699300-5f1f-11eb-862a-e4fe90eab13f.jpg)

**Comment by nitrocode** [comment]
It looks like it's forcing a replacement due to adding a load balancer. It only ignores the `task_definition` argument changes.

**Comment by mhmdio** [comment]
Hmm, could be, since I'm using CodeDeploy with blue green, each time, I need to flip target groups between blue and green. this could affect the way it worked.

**Comment by nitrocode** [comment]
I don't think this is a bug with the module. If you want to ignore a task definition based on the load balancer, you can now do this by passing in a task definition arn from outside the module.
