### ISSUE TITLE
Allow using EC2 instance role

### ISSUE THREAD

**Issue by j00p34** [cloudposse/terraform-aws-ecs-alb-service-task#94]
## Describe the Feature

Task execution role should be optional

## Expected Behavior

Task execution role can be disabled

## Use Case

Usage of task execution role replaces EC2 instance role.
We would like to continue to be able to use instance roles

**Comment by nitrocode** [comment]
That's considered bad practices. Every task should use its own iam role. 

If you really want to do this, you can assign the ec2 iam role as your `var.task_exec_role_arn`

**Comment by j00p34** [comment]
We have a very specific use case for this :-)

Thank you for your reply

**Comment by nitrocode** [comment]
@j00p34 does my suggestion work for you ? or should we consider making the argument optional ?

**Comment by j00p34** [comment]
@nitrocode thanks for your reply, sorry for my late response. No, it actually doesn't work for our use case, we have a very specific environment, we can only use the instance role as is. It would be great if you could make it optional. Although I completely understand why it's bad practice and it may be better to keep it like it is, so people don't stray from the best practice.

**Comment by nitrocode** [comment]
What if you set the variable to `null` ? Would it work?

**Comment by j00p34** [comment]
I'll have to look into it again, as I can't remember why it didn't work. It probably had to do something with permissions.
